version: '3'

services:

  yt-service:
    # env_file:
    #   - .env
    build:
      context: ./yt_service
      dockerfile: service.Dockerfile
    image: "yt-service"
    restart: always
    tty: true
    # command: /usr/bin/supervisord -n
    command: python3 manage.py runserver 0.0.0.0:9090
    ports:
      - "9090:9090"
    networks:
      - yt-network
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure

networks:
  yt-network:
